ENVARGS=""
for pass_env in NIX_BINTOOLS NIX_BINTOOLS_WRAPPER_x86_64_unknown_linux_gnu_TARGET_HOST NIX_BUILD_TOP NIX_CC NIX_CFLAGS_COMPILE NIX_CC_WRAPPER_x86_64_unknown_linux_gnu_TARGET_HOST NIX_ENFORCE_NO_NATIVE NIX_HARDENING_ENABLE NIX_LDFLAGS NIX_LIB64_IN_SELF_RPATH NIX_NO_SELF_RPATH NIX_PATH NIX_SSL_CERT_FILE NIX_STORE
do
    ENVARGS="${ENVARGS} --action_env=${pass_env} --test_env=${pass_env}"
done
bazel build --jobs 2 -s $ENVARGS $@
